# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2518cde4131d131055d6b6a9f7333c7e43d25e89d60b97cb82ab697b66aa6d7155286c3e1cd7cbcd8fe7a04247c77808ee049b355bb75907aabaef56f4d783b7

test:
  secret_key_base: af00bd961614116a15d5c580b6b93925c853822a6c38c02d9a50e07ad624306d275e39544828cdf4ecfb9441348658192e51d53e9d4e946daaed2d79e1d8f5af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
